// Swop transaction-success one-liners — the ‘While you wait…’ dopamine card
// on the post-swap / post-send celebration modal. Single source of truth shared
// by the swap and send success screens (mirrors the mobile app’s jokes list).

export const AI_JOKES: string[] = [
  "Congrats. Your portfolio is now down in a whole new currency.",
  "You made money today. Statistically terrifying. Don’t get used to it.",
  "Most responsible thing you’ve done with money since you quit dog coins.",
  "It cleared. Your ex still won’t answer, but the blockchain always does.",
  "You held for a whole 20 minutes. Warren Buffett is shaking.",
  "Fees were 0.5%. Less than you tip, way less than you cry.",
  "Somewhere a Coinbase exec just felt a cold breeze and doesn’t know why.",
  "You didn’t get liquidated today. Put that on the fridge.",
  "That’s real money now. Not “I’ll pay you back” money. Actual money.",
  "You bought high before. This time you only bought medium. Growth.",
  "Someone asked what you’re doing on your phone. Say “winning.” It’s true.",
  "That trade cleared faster than your last three relationships.",
  "You saved on fees. Now go lose it on a cartoon frog, I can’t stop you.",
  "Green candle, clean swap, low fee. Enjoy it — the market has a curfew.",
  "One good trade doesn’t undo the portfolio. But we’re proud anyway.",
  "You’re basically a hedge fund now. A small, sad, one-man hedge fund.",
  "This is the closest you’ve come to a savings account in years.",
  "Your mom still thinks crypto is a scam. Today she’s only half right.",
  "A trade that didn’t lose money. Frame it, it won’t happen twice.",
  "Coinbase would’ve taken double. Buy yourself a sandwich with the diff.",
  "You didn’t panic sell. Character development, right in front of us.",
  "Somewhere your financial advisor felt that and doesn’t know why.",
  "That’s more discipline than you showed at the buffet last weekend.",
  "The good news: it cleared. The bad news: now you’ll do it again.",
  "You bought the dip. It kept dipping. But hey, this one worked.",
  "Not financial advice, but that was the least dumb thing you’ve done.",
  "You’re up. Don’t check again for an hour, you’ll ruin it.",
  "Faster than your Uber, cheaper than your ex, cleaner than your room.",
  "That’s the most action your wallet has seen since payday.",
  "Congrats, degen. Touch grass before you open the app again.",
  "You traded like an adult today. We won’t tell anyone.",
  "Low fees, quick swap. Almost like the system worked for once.",
  "You outperformed everyone still arguing about it on Twitter.",
  "That settled in 1.3 seconds. Your gym membership never settled at all.",
  "Real money moved and nobody got scammed. Historic day.",
  "Your portfolio thanks you. Your sleep schedule does not.",
  "You made a decision without a Discord telling you to. Growth.",
  "Half the fee of Coinbase. Twice the confidence you can’t back up.",
  "You didn’t ape into it this time. Someone’s maturing.",
  "That’s a W. Small W. But your W column needed the company.",
  "The trade worked. Now quit while the universe isn’t looking.",
  "You saved on fees again. It’s almost like reading things pays off.",
  "Cleaner exit than you made from that party in 2019.",
  "Your wallet did more today than your last three New Year’s resolutions.",
  "That’s money you can’t explain to your accountant. Enjoy it quietly.",
  "One green trade. Statistically you’re due for chaos, so savor it.",
  "You beat the market for exactly one transaction. Legend.",
  "You didn’t get rugged. Standards are low but we’re celebrating.",
  "Faster confirmation than your doctor gives you. And less bad news.",
  "You spent less on fees than you did on that jacket you never wear.",
  "That’s a swap your future self won’t have to apologize for.",
  "You moved money and the world didn’t end. Overachiever.",
  "Coinbase charges 1%. Phantom 0.85%. You just outsmarted both.",
  "Look at you, making moves instead of excuses.",
  "You didn’t fat-finger the amount. Small victories, big relief.",
  "That’s the calmest you’ve been since the last bull run.",
  "You traded and didn’t immediately regret it. New personal best.",
  "Your ex is somewhere doing worse with their money. Probably.",
  "Clean swap, low fee, no tears. Write it in the diary.",
  "You held your nerve and your bags. Both, at the same time.",
  "That went through smoother than your last job interview.",
  "You saved on fees. Don’t donate it back to a frog coin, I beg you.",
  "A responsible financial move. Your group chat won’t recognize you.",
  "You didn’t need a guru for that one. Refund your subscription.",
  "That’s money that stays money. Rare species around here.",
  "You outlasted the paper hands. Barely, but it counts.",
  "The trade cleared before your coffee got cold. Efficiency.",
  "You made money and it wasn’t even an accident this time.",
  "Somewhere a TradFi banker just lost a client and it’s you.",
  "You did the thing. The smart thing. We’re as shocked as you are.",
  "Low fee, fast swap. The app did its job, now don’t undo it.",
  "That’s a trade you can actually tell your partner about.",
  "You’re one good decision away from a personality. Keep going.",
  "You beat Coinbase’s fee and their app didn’t even fight back.",
  "That settled faster than any argument you’ve ever had.",
  "You didn’t buy the top. Take the win, hero, it’s a big one.",
  "Money moved, fees stayed tiny, no one cried. Best-case scenario.",
  "You traded like you read the whitepaper. You didn’t, but still.",
  "That’s more upside than your fantasy team gave you all season.",
  "You saved a few bucks on fees. Now don’t YOLO it into a meme.",
  "You made a move your accountant would almost approve of.",
  "That cleared clean. Unlike your browser history.",
  "You didn’t get liquidated, ghosted, or scammed. Triple win.",
  "The trade’s done. Close the app. I’m serious. Close it.",
  "You handled money like an adult for exactly one transaction.",
  "That’s the fastest good decision you’ll make all week.",
  "You just paid half what Coinbase wanted. Spite is profitable.",
  "One clean swap. Your therapist will be so proud, don’t ruin it.",
  "You didn’t overthink it and it worked. Wild concept.",
  "That’s a trade with no asterisk. Frame it before you forget.",
  "You moved fast, paid little, panicked none. Elite behavior.",
  "Your wallet’s having a better day than your credit score.",
  "You saved on fees. The universe now owes you nothing, we’re even.",
  "That went through. Your excuses, for once, did not.",
  "You beat the fee, beat the spread, beat your own worst instinct.",
  "A green trade on a random Tuesday. Take it and run.",
  "You did math and it paid off. Somewhere a teacher is weeping.",
  "That’s clean money, quick money, low-fee money. Go log off happy.",
  "You didn’t hesitate and it paid off. Frame this feeling.",
  "Fast swap, tiny fee, zero regret. The rare trifecta. Go celebrate.",
];
