'use client';

import { Bot } from 'lucide-react';

// Shared "🤖 <owner>'s agent" pill rendered on venue feed cards when a post was
// auto-generated by a user's autonomous agent. Reuses the indigo agent-pill
// styling already used on AgentTradeFeedCard so venue-specific agent trades
// read consistently with the unified agent-trade card.

export interface AgentBadgeAgent {
  isAgentTrade?: boolean;
  agentId?: string;
  agentName?: string;
}

interface AgentBadgeProps {
  /** The post's `agent` block — the badge only renders when isAgentTrade. */
  agent?: AgentBadgeAgent | null;
  /**
   * Owner handle to display ("<owner>'s agent"). Derive from
   * smartsiteEnsName / smartsiteUserName at the call site; falls back to "You".
   */
  ownerHandle?: string | null;
  className?: string;
}

export default function AgentBadge({
  agent,
  ownerHandle,
  className,
}: AgentBadgeProps) {
  if (!agent?.isAgentTrade) return null;

  const owner = (ownerHandle && String(ownerHandle).trim()) || 'You';
  // The agent's own name (e.g. "agent-travis.swop.id") used as the tooltip.
  const agentName = agent.agentName || 'agent';

  return (
    <span
      className={`inline-flex min-w-0 items-center gap-1.5 rounded-full border border-indigo-200 bg-indigo-50 px-2.5 py-1 font-mono text-[10px] font-black text-indigo-600 ${
        className || ''
      }`}
      title={agentName}
      data-testid="agent-badge"
    >
      <Bot className="h-3 w-3 shrink-0" aria-hidden="true" />
      <span className="truncate">🤖 {owner}&apos;s agent</span>
    </span>
  );
}
