"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { Pause, Play, SkipBack, SkipForward } from "lucide-react";

type Track = { id: string; name: string; url: string; status: "ready" | "processing" };

export default function MusicCard({ config, mode = "public" }: { config: { albumName?: string; coverUrl?: string; tracks?: Track[] }; mode?: "public" | "builder" }) {
  const tracks = config.tracks || []; const [index, setIndex] = useState(0); const [playing, setPlaying] = useState(false); const audio = useRef<HTMLAudioElement>(null); const track = tracks[index];
  const select = (next: number) => { if (!tracks.length) return; setIndex((next + tracks.length) % tracks.length); setPlaying(true); setTimeout(() => void audio.current?.play(), 0); };
  const toggle = () => { if (!audio.current || mode === "builder") return; if (playing) audio.current.pause(); else void audio.current.play(); setPlaying(!playing); };
  return <section className="rounded-[24px] border border-[#e8dfd0] bg-[#f7f2e8] p-5 shadow-sm"><h3 className="text-lg font-black">{config.albumName || "Album"}</h3><div className="relative mx-auto mt-4 h-44 w-52"><div className={`absolute left-5 top-0 h-44 w-44 overflow-hidden rounded-full border-4 border-[#292929] bg-[#141414] ${playing ? "animate-spin [animation-duration:5s]" : ""}`}>{config.coverUrl && <Image src={config.coverUrl} alt="" fill className="scale-50 rounded-full object-cover" />}<span className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#f7f2e8]" /></div><span className="absolute right-3 top-1 h-32 w-2 rotate-[18deg] rounded-full bg-[#b6a68c]" /></div><p className="mt-2 truncate text-center text-sm font-bold">{track?.name || "Add a track"}</p><audio ref={audio} src={track?.url} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => select(index + 1)} controls={mode === "public"} className="mt-3 h-9 w-full" /><div className="mt-3 flex items-center justify-center gap-7"><button type="button" disabled={mode === "builder"} onClick={() => select(index - 1)}><SkipBack size={20} /></button><button type="button" disabled={mode === "builder"} onClick={toggle} className="grid h-12 w-12 place-items-center rounded-full bg-black text-white">{playing ? <Pause size={21} /> : <Play size={21} />}</button><button type="button" disabled={mode === "builder"} onClick={() => select(index + 1)}><SkipForward size={20} /></button></div><div className="mt-4 flex flex-col gap-1">{tracks.map((item, itemIndex) => <button type="button" key={item.id} disabled={mode === "builder"} onClick={() => select(itemIndex)} className={`flex items-center rounded-xl px-3 py-2 text-left text-sm ${itemIndex === index ? "bg-white" : "bg-white/40"}`}><span className="min-w-0 flex-1 truncate font-bold">{itemIndex + 1}. {item.name}</span><span className="text-[10px] text-gray-500">{item.status === "processing" ? "Processing" : itemIndex === index && playing ? "Playing" : "Ready"}</span></button>)}</div></section>;
}
