export const HYPERLIQUID_INFO_PROXY_MAX_ATTEMPTS = 2;
export const HYPERLIQUID_INFO_PROXY_ATTEMPT_TIMEOUT_MS = 8_000;
export const HYPERLIQUID_INFO_PROXY_RETRY_DELAY_MS = 250;

export const HYPERLIQUID_INFO_PROXY_RETRY_WINDOW_MS =
  HYPERLIQUID_INFO_PROXY_MAX_ATTEMPTS *
    HYPERLIQUID_INFO_PROXY_ATTEMPT_TIMEOUT_MS +
  (HYPERLIQUID_INFO_PROXY_MAX_ATTEMPTS - 1) *
    HYPERLIQUID_INFO_PROXY_RETRY_DELAY_MS;

// Keep client-side read callers alive long enough to benefit from the proxy's
// full retry budget plus a small response/serialization cushion.
export const HYPERLIQUID_USER_FILLS_REQUEST_TIMEOUT_MS =
  HYPERLIQUID_INFO_PROXY_RETRY_WINDOW_MS + 1_000;
