"use client";
import { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { FileText, Loader, Plus, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import { handleCreateWidget } from "@/actions/widget";
import { PrimaryButton } from "@/components/ui/Button/PrimaryButton";
import AiChatCard from "@/components/publicProfile/widgets/AiChatCard";
import useSmartSiteApiDataStore from "@/zustandStore/UpdateSmartsiteInfo";

export default function AddAiChat({ onCloseModal }: { onCloseModal: () => void }) {
  const site: any = useSmartSiteApiDataStore((state) => state); const [token, setToken] = useState(""); const [name, setName] = useState("SmartSite Concierge"); const [personality, setPersonality] = useState("Friendly, concise, and helpful."); const [documents, setDocuments] = useState<any[]>([]); const [starters, setStarters] = useState(["What can you help me with?", "Tell me about this project", "How do I get started?"]); const [blinkId, setBlinkId] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => setToken(Cookies.get("access-token") || ""), []);
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); const added = await Promise.all(files.map(async (file, index) => { if (!file.name.toLowerCase().endsWith(".md")) throw new Error("Only .md files are supported"); const content = await file.text(); if (content.length > 50000) throw new Error(`${file.name} is too large`); return { id: `doc-${documents.length + index + 1}`, name: file.name, content, status: "trained" }; })); setDocuments((current) => [...current, ...added].slice(0, 10)); };
  const blink = site.info?.redeemLink?.find((item: any) => item._id === blinkId); const config = { name, personality, documents, starters: starters.filter(Boolean), blink: blink ? { id: blink._id, name: blink.mintName || blink.name, type: blink.tokenType === "Token" ? "Token" : "NFT", imageUrl: blink.imageUrl, link: blink.link } : null };
  const save = async () => { setSaving(true); try { const result = await handleCreateWidget({ micrositeId: site._id, widgetType: "aiChat", config }, token); if (result?.state !== "success") throw new Error(result?.message); toast.success("Chat added"); onCloseModal(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add Chat"); } finally { setSaving(false); } };
  const input = "w-full rounded-xl border border-black/10 px-3 py-2.5 text-sm outline-none";
  return <div className="mx-auto grid max-w-4xl gap-6 md:grid-cols-2"><div className="flex flex-col gap-4"><h2 className="text-xl font-bold">AI Chat</h2><label className="text-xs font-bold text-gray-500">Name<input className={`${input} mt-1`} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-xs font-bold text-gray-500">Personality<textarea className={`${input} mt-1 min-h-20`} value={personality} onChange={(event) => setPersonality(event.target.value)} /></label><div><div className="flex items-center justify-between"><p className="text-xs font-bold text-gray-500">Knowledge base</p><label className="cursor-pointer rounded-full bg-gray-950 px-3 py-1.5 text-xs font-bold text-white"><Plus size={13} className="inline" /> Add .md<input type="file" accept=".md,text/markdown" multiple className="hidden" onChange={(event) => void upload(event)} /></label></div>{documents.map((doc) => <div key={doc.id} className="mt-2 flex items-center gap-2 rounded-xl bg-gray-100 p-3"><FileText size={16} /><span className="flex-1 truncate text-sm font-semibold">{doc.name}</span><span className="text-xs text-emerald-600">Trained</span><button onClick={() => setDocuments((current) => current.filter((item) => item.id !== doc.id))}><Trash2 size={15} /></button></div>)}</div><p className="text-xs font-bold text-gray-500">Starter questions</p>{starters.map((starter, index) => <input key={index} className={input} value={starter} onChange={(event) => setStarters((current) => current.map((item, i) => i === index ? event.target.value : item))} />)}<label className="text-xs font-bold text-gray-500">Attach a Blink<select className={`${input} mt-1`} value={blinkId} onChange={(event) => setBlinkId(event.target.value)}><option value="">None</option>{site.info?.redeemLink?.map((item: any) => <option key={item._id} value={item._id}>{item.mintName || item.name || "Blink"}</option>)}</select></label><PrimaryButton onClick={save} disabled={saving}>{saving ? <Loader className="mx-auto h-5 w-5 animate-spin" /> : "Save Chat"}</PrimaryButton></div><AiChatCard config={config} mode="builder" /></div>;
}
