"use client";
import { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { ArrowDown, ArrowUp, Loader, Trash2, Upload } from "lucide-react";
import toast from "react-hot-toast";
import { handleCreateWidget } from "@/actions/widget";
import MusicCard from "@/components/publicProfile/widgets/MusicCard";
import { PrimaryButton } from "@/components/ui/Button/PrimaryButton";
import { sendCloudinaryFile } from "@/lib/SendCloudinaryAnyFile";
import useSmartSiteApiDataStore from "@/zustandStore/UpdateSmartsiteInfo";
type Track = { id: string; name: string; url: string; status: "ready" | "processing" };
export default function AddMusic({ onCloseModal }: { onCloseModal: () => void }) {
  const site: any = useSmartSiteApiDataStore((state) => state); const [token, setToken] = useState(""); const [albumName, setAlbumName] = useState("My Album"); const [coverUrl, setCoverUrl] = useState(""); const [tracks, setTracks] = useState<Track[]>([]); const [busy, setBusy] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => setToken(Cookies.get("access-token") || ""), []);
  const cover = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { setCoverUrl(await sendCloudinaryFile(await readDataUrl(file), file.type, file.name)); } catch { toast.error("Cover upload failed"); } finally { setBusy(false); } };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const selected = Array.from(event.target.files || []); if (!selected.length) return; setBusy(true); const pending = selected.map((file, index) => ({ id: `track-${Date.now()}-${index}`, name: file.name, url: "", status: "processing" as const })); setTracks((current) => [...current, ...pending]); try { const ready = await Promise.all(selected.map(async (file, index) => ({ ...pending[index], url: await sendCloudinaryFile(await readDataUrl(file), file.type || "audio/mpeg", file.name), status: "ready" as const }))); setTracks((current) => current.map((track) => ready.find((item) => item.id === track.id) || track)); } catch { setTracks((current) => current.filter((track) => !pending.some((item) => item.id === track.id))); toast.error("Track upload failed"); } finally { setBusy(false); } };
  const move = (index: number, delta: number) => setTracks((current) => { const next = [...current], target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const save = async () => { if (!albumName.trim() || !coverUrl || !tracks.length || tracks.some((track) => !track.url)) return toast.error("Add an album name, cover, and ready tracks"); setSaving(true); try { const result = await handleCreateWidget({ micrositeId: site._id, widgetType: "music", config: { albumName: albumName.trim(), coverUrl, tracks } }, token); if (result?.state !== "success") throw new Error(); toast.success("Album added"); onCloseModal(); } catch { toast.error("Could not save album"); } finally { setSaving(false); } };
  const input = "w-full rounded-xl border border-black/10 px-3 py-2.5 text-sm outline-none"; return <div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-2"><div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Music / MP3</h2><input className={input} value={albumName} onChange={(event) => setAlbumName(event.target.value)} placeholder="Album name" /><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-black/20 px-4 py-3 text-sm font-bold"><Upload size={16} />{coverUrl ? "Change cover" : "Upload cover"}<input type="file" accept="image/*" className="hidden" onChange={(event) => void cover(event)} /></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-bold text-white"><Upload size={16} />Upload MP3s<input type="file" accept="audio/*,.mp3" multiple className="hidden" onChange={(event) => void upload(event)} /></label>{tracks.map((track, index) => <div key={track.id} className="flex items-center gap-2 rounded-xl bg-gray-100 p-3"><span className="min-w-0 flex-1 truncate text-sm font-bold">{track.name}</span><span className="text-[10px] text-gray-500">{track.status === "ready" ? "Ready" : "Processing"}</span><button type="button" onClick={() => move(index, -1)}><ArrowUp size={15} /></button><button type="button" onClick={() => move(index, 1)}><ArrowDown size={15} /></button><button type="button" onClick={() => setTracks((current) => current.filter((item) => item.id !== track.id))}><Trash2 size={15} className="text-red-500" /></button></div>)}<PrimaryButton onClick={() => void save()} disabled={busy || saving}>{busy || saving ? <Loader className="mx-auto h-5 w-5 animate-spin" /> : "Save Album"}</PrimaryButton></div><MusicCard config={{ albumName, coverUrl, tracks }} mode="builder" /></div>;
}
function readDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(new Error("File read failed")); reader.readAsDataURL(file); }); }
