"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import { filterVideoFilesByPlan } from "@/lib/videoLimits";
import Cookies from "js-cookie";
import { Loader, Plus, Trash2, Upload, X } from "lucide-react";
import toast from "react-hot-toast";
import { handleCreateWidget } from "@/actions/widget";
import MediaCarouselCard from "@/components/publicProfile/widgets/MediaCarouselCard";
import { PrimaryButton } from "@/components/ui/Button/PrimaryButton";
import { sendCloudinaryFile } from "@/lib/SendCloudinaryAnyFile";
import useSmartSiteApiDataStore from "@/zustandStore/UpdateSmartsiteInfo";
type Media = { id: string; url: string; type: "photo" | "video" }; type Carousel = { id: string; name: string; items: Media[] };
export default function AddMediaCarousel({ onCloseModal }: { onCloseModal: () => void }) {
  const site: any = useSmartSiteApiDataStore((state) => state); const [token, setToken] = useState(""); const [carousels, setCarousels] = useState<Carousel[]>([{ id: "carousel-1", name: "Highlights", items: [] }]); const [busyId, setBusyId] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => setToken(Cookies.get("access-token") || ""), []);
  const upload = async (carouselId: string, event: React.ChangeEvent<HTMLInputElement>) => { const files = await filterVideoFilesByPlan(Array.from(event.target.files || [])); if (!files.length) return; setBusyId(carouselId); try { const added = await Promise.all(files.map(async (file, index) => ({ id: `media-${Date.now()}-${index}`, url: await sendCloudinaryFile(await readDataUrl(file), file.type, file.name), type: file.type.startsWith("video/") ? "video" as const : "photo" as const }))); setCarousels((current) => current.map((carousel) => carousel.id === carouselId ? { ...carousel, items: [...carousel.items, ...added] } : carousel)); } catch { toast.error("Media upload failed"); } finally { setBusyId(""); } };
  const save = async () => { if (!carousels.length || carousels.some((carousel) => !carousel.name.trim() || !carousel.items.length)) return toast.error("Every named carousel needs media"); setSaving(true); try { const result = await handleCreateWidget({ micrositeId: site._id, widgetType: "mediaCarousel", config: { carousels: carousels.map((carousel) => ({ ...carousel, name: carousel.name.trim() })) } }, token); if (result?.state !== "success") throw new Error(); toast.success("Carousels added"); onCloseModal(); } catch { toast.error("Could not save carousels"); } finally { setSaving(false); } };
  const input = "w-full rounded-xl border border-black/10 px-3 py-2.5 text-sm outline-none"; return <div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-2"><div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Photo / Video Carousel</h2>{carousels.map((carousel) => <div key={carousel.id} className="rounded-2xl border border-black/10 p-3"><div className="flex gap-2"><input className={input} value={carousel.name} onChange={(event) => setCarousels((current) => current.map((item) => item.id === carousel.id ? { ...item, name: event.target.value } : item))} placeholder="Carousel name" /><button type="button" onClick={() => setCarousels((current) => current.filter((item) => item.id !== carousel.id))}><Trash2 size={17} className="text-red-500" /></button></div><div className="mt-3 flex gap-2 overflow-x-auto">{carousel.items.map((item) => <div key={item.id} className="relative h-20 w-24 flex-none overflow-hidden rounded-xl bg-gray-100">{item.type === "video" ? <video src={item.url} className="h-full w-full object-cover" /> : <img src={item.url} alt="" className="h-full w-full object-cover" />}<button type="button" className="absolute right-1 top-1 rounded-full bg-black/70 p-1 text-white" onClick={() => setCarousels((current) => current.map((entry) => entry.id === carousel.id ? { ...entry, items: entry.items.filter((media) => media.id !== item.id) } : entry))}><X size={11} /></button></div>)}</div><label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-gray-100 px-3 py-2 text-xs font-bold">{busyId === carousel.id ? <Loader className="h-4 w-4 animate-spin" /> : <Upload size={14} />}Add photos or videos<input type="file" accept="image/*,video/*" multiple className="hidden" onChange={(event) => void upload(carousel.id, event)} /></label></div>)}<button type="button" onClick={() => setCarousels((current) => [...current, { id: `carousel-${Date.now()}`, name: `Carousel ${current.length + 1}`, items: [] }])} className="flex items-center justify-center gap-2 rounded-xl border border-dashed border-black/20 px-4 py-3 text-sm font-bold"><Plus size={16} />Add carousel</button><PrimaryButton onClick={() => void save()} disabled={saving || Boolean(busyId)}>{saving ? <Loader className="mx-auto h-5 w-5 animate-spin" /> : "Save Carousels"}</PrimaryButton></div><MediaCarouselCard config={{ carousels }} mode="builder" /></div>;
}
function readDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(new Error("File read failed")); reader.readAsDataURL(file); }); }
